services:
  - type: web
    name: fosse-equipment-monitor
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
    autoDeploy: true
  - type: cron
    name: create-users
    schedule: "0 0 * * *"  # Daily at midnight
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py create_users"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
